#!/usr/bin/env python3
"""生成物から「生成時刻」を取り除き、ビルドを決定的にする。

    python3 scripts/normalize_generated.py <file> [<file> ...]

TEI Stylesheets の odd2relax.xsl / extract-isosch.xsl / odd2html.xsl は、
生成時刻をそれぞれの出力に埋め込む。そのままだと同じ ODD から作っても毎回
ファイルが変わり、「生成物が ODD と一致するか」を CI で検査できない
（.github/workflows/validate.yml の "Generated schema must match what is committed"）。

時刻の部分だけを固定文言に置き換える。内容は変えない。
"""

import pathlib
import re
import sys

TIMESTAMP = r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z"

RULES = [
    # extract-isosch.xsl
    (re.compile(r"<!-- This file generated " + TIMESTAMP + r" by 'extract-isosch\.xsl'\. -->"),
     "<!-- This file generated by 'extract-isosch.xsl'. Do not edit; edit the ODD. -->"),
    # odd2relax.xsl
    (re.compile(r"Schema generated from ODD source " + TIMESTAMP + r"\."),
     "Schema generated from ODD source."),
    # odd2html.xsl
    (re.compile(r"on " + TIMESTAMP + r"\."),
     "from the ODD."),
]


def main(argv):
    if len(argv) < 2:
        print(__doc__, file=sys.stderr)
        return 2

    for name in argv[1:]:
        path = pathlib.Path(name)
        if not path.exists():
            print(f"見つかりません: {name}", file=sys.stderr)
            return 1
        text = path.read_text(encoding="utf-8")
        original = text
        for pattern, replacement in RULES:
            text = pattern.sub(replacement, text)
        if text != original:
            path.write_text(text, encoding="utf-8")

        # 取りこぼしたタイムスタンプが残っていれば知らせる（CI が謎に落ちるのを防ぐ）
        left = re.findall(TIMESTAMP, text)
        if left:
            print(f"警告: {name} に時刻らしき文字列が残っています: {sorted(set(left))[:3]}",
                  file=sys.stderr)

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
